# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import suggestions_pb2 as suggestions__pb2


class SuggestionsServiceStub(object):
    """
    SuggestionsService provides book recommendations based on the provided book name.

    The service consists of a single RPC method:
    - GetSuggestions: Takes a SuggestionRequest containing a book name and returns a SuggestionResponse
    with a list of suggested books.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSuggestions = channel.unary_unary(
                '/suggestions.SuggestionsService/GetSuggestions',
                request_serializer=suggestions__pb2.SuggestionRequest.SerializeToString,
                response_deserializer=suggestions__pb2.SuggestionResponse.FromString,
                )


class SuggestionsServiceServicer(object):
    """
    SuggestionsService provides book recommendations based on the provided book name.

    The service consists of a single RPC method:
    - GetSuggestions: Takes a SuggestionRequest containing a book name and returns a SuggestionResponse
    with a list of suggested books.
    """

    def GetSuggestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSuggestions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSuggestions,
                    request_deserializer=suggestions__pb2.SuggestionRequest.FromString,
                    response_serializer=suggestions__pb2.SuggestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'suggestions.SuggestionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SuggestionsService(object):
    """
    SuggestionsService provides book recommendations based on the provided book name.

    The service consists of a single RPC method:
    - GetSuggestions: Takes a SuggestionRequest containing a book name and returns a SuggestionResponse
    with a list of suggested books.
    """

    @staticmethod
    def GetSuggestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suggestions.SuggestionsService/GetSuggestions',
            suggestions__pb2.SuggestionRequest.SerializeToString,
            suggestions__pb2.SuggestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
