# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0bsuggestions\"!\n\x11SuggestionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"%\n\x12SuggestionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2g\n\x12SuggestionsService\x12Q\n\x0eGetSuggestions\x12\x1e.suggestions.SuggestionRequest\x1a\x1f.suggestions.SuggestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUGGESTIONREQUEST']._serialized_start=34
  _globals['_SUGGESTIONREQUEST']._serialized_end=67
  _globals['_SUGGESTIONRESPONSE']._serialized_start=69
  _globals['_SUGGESTIONRESPONSE']._serialized_end=106
  _globals['_SUGGESTIONSSERVICE']._serialized_start=108
  _globals['_SUGGESTIONSSERVICE']._serialized_end=211
# @@protoc_insertion_point(module_scope)
