# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0bsuggestions\">\n\rSuggestedBook\x12\x0e\n\x06\x62ookId\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\"8\n\x11SuggestionRequest\x12\x11\n\tbook_name\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\"[\n\x12SuggestionResponse\x12\x33\n\x0fsuggested_books\x18\x01 \x03(\x0b\x32\x1a.suggestions.SuggestedBook\x12\x10\n\x08\x61pproved\x18\x02 \x01(\x08\x32g\n\x12SuggestionsService\x12Q\n\x0eGetSuggestions\x12\x1e.suggestions.SuggestionRequest\x1a\x1f.suggestions.SuggestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUGGESTEDBOOK']._serialized_start=34
  _globals['_SUGGESTEDBOOK']._serialized_end=96
  _globals['_SUGGESTIONREQUEST']._serialized_start=98
  _globals['_SUGGESTIONREQUEST']._serialized_end=154
  _globals['_SUGGESTIONRESPONSE']._serialized_start=156
  _globals['_SUGGESTIONRESPONSE']._serialized_end=247
  _globals['_SUGGESTIONSSERVICE']._serialized_start=249
  _globals['_SUGGESTIONSSERVICE']._serialized_end=352
# @@protoc_insertion_point(module_scope)
