# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment_service.proto\x12\x0fpayment_service\"Q\n\x15PaymentPrepareRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"\\\n\x0cVoteResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12#\n\x04vote\x18\x02 \x01(\x0e\x32\x15.payment_service.Vote\x12\x0f\n\x07message\x18\x03 \x01(\t\",\n\x12TransactionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"b\n\x0b\x41\x63kResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12*\n\x06status\x18\x02 \x01(\x0e\x32\x1a.payment_service.AckStatus\x12\x0f\n\x07message\x18\x03 \x01(\t*=\n\x04Vote\x12\x14\n\x10VOTE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bVOTE_COMMIT\x10\x01\x12\x0e\n\nVOTE_ABORT\x10\x02*B\n\tAckStatus\x12\x13\n\x0f\x41\x43K_UNSPECIFIED\x10\x00\x12\x0f\n\x0b\x41\x43K_SUCCESS\x10\x01\x12\x0f\n\x0b\x41\x43K_FAILURE\x10\x02\x32\xfb\x01\n\x0ePaymentService\x12P\n\x07Prepare\x12&.payment_service.PaymentPrepareRequest\x1a\x1d.payment_service.VoteResponse\x12K\n\x06\x43ommit\x12#.payment_service.TransactionRequest\x1a\x1c.payment_service.AckResponse\x12J\n\x05\x41\x62ort\x12#.payment_service.TransactionRequest\x1a\x1c.payment_service.AckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTE']._serialized_start=365
  _globals['_VOTE']._serialized_end=426
  _globals['_ACKSTATUS']._serialized_start=428
  _globals['_ACKSTATUS']._serialized_end=494
  _globals['_PAYMENTPREPAREREQUEST']._serialized_start=42
  _globals['_PAYMENTPREPAREREQUEST']._serialized_end=123
  _globals['_VOTERESPONSE']._serialized_start=125
  _globals['_VOTERESPONSE']._serialized_end=217
  _globals['_TRANSACTIONREQUEST']._serialized_start=219
  _globals['_TRANSACTIONREQUEST']._serialized_end=263
  _globals['_ACKRESPONSE']._serialized_start=265
  _globals['_ACKRESPONSE']._serialized_end=363
  _globals['_PAYMENTSERVICE']._serialized_start=497
  _globals['_PAYMENTSERVICE']._serialized_end=748
# @@protoc_insertion_point(module_scope)
