# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x05\x66raud\"\x1c\n\x0c\x46raudRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rFraudResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2H\n\x0c\x46raudService\x12\x38\n\x0b\x44\x65tectFraud\x12\x13.fraud.FraudRequest\x1a\x14.fraud.FraudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAUDREQUEST']._serialized_start=32
  _globals['_FRAUDREQUEST']._serialized_end=60
  _globals['_FRAUDRESPONSE']._serialized_start=62
  _globals['_FRAUDRESPONSE']._serialized_end=94
  _globals['_FRAUDSERVICE']._serialized_start=96
  _globals['_FRAUDSERVICE']._serialized_end=168
# @@protoc_insertion_point(module_scope)
