# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x05\x66raud\")\n\x08UserInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\"E\n\x0e\x43reditCardInfo\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"\x9b\x01\n\x0c\x46raudRequest\x12\"\n\tuser_info\x18\x01 \x01(\x0b\x32\x0f.fraud.UserInfo\x12*\n\x0b\x63redit_card\x18\x02 \x01(\x0b\x32\x15.fraud.CreditCardInfo\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x10\n\x08order_id\x18\x05 \x01(\t\"E\n\rFraudResponse\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0e\n\x06reason\x18\x03 \x01(\t2\xc6\x01\n\x0c\x46raudService\x12\x38\n\x0b\x44\x65tectFraud\x12\x13.fraud.FraudRequest\x1a\x14.fraud.FraudResponse\x12:\n\rCheckUserData\x12\x13.fraud.FraudRequest\x1a\x14.fraud.FraudResponse\x12@\n\x13\x43heckCreditCardData\x12\x13.fraud.FraudRequest\x1a\x14.fraud.FraudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERINFO']._serialized_start=32
  _globals['_USERINFO']._serialized_end=73
  _globals['_CREDITCARDINFO']._serialized_start=75
  _globals['_CREDITCARDINFO']._serialized_end=144
  _globals['_FRAUDREQUEST']._serialized_start=147
  _globals['_FRAUDREQUEST']._serialized_end=302
  _globals['_FRAUDRESPONSE']._serialized_start=304
  _globals['_FRAUDRESPONSE']._serialized_end=373
  _globals['_FRAUDSERVICE']._serialized_start=376
  _globals['_FRAUDSERVICE']._serialized_end=574
# @@protoc_insertion_point(module_scope)
