# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import order_executor_pb2 as order__executor__pb2


class OrderExecutorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/orderexecutor.OrderExecutorService/RequestVote',
                request_serializer=order__executor__pb2.VoteRequest.SerializeToString,
                response_deserializer=order__executor__pb2.VoteResponse.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/orderexecutor.OrderExecutorService/Heartbeat',
                request_serializer=order__executor__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=order__executor__pb2.HeartbeatResponse.FromString,
                )
        self.GetExecutorStatus = channel.unary_unary(
                '/orderexecutor.OrderExecutorService/GetExecutorStatus',
                request_serializer=order__executor__pb2.StatusRequest.SerializeToString,
                response_deserializer=order__executor__pb2.StatusResponse.FromString,
                )


class OrderExecutorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestVote(self, request, context):
        """Leader election related RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExecutorStatus(self, request, context):
        """For monitoring/status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=order__executor__pb2.VoteRequest.FromString,
                    response_serializer=order__executor__pb2.VoteResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=order__executor__pb2.HeartbeatRequest.FromString,
                    response_serializer=order__executor__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetExecutorStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecutorStatus,
                    request_deserializer=order__executor__pb2.StatusRequest.FromString,
                    response_serializer=order__executor__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderexecutor.OrderExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderExecutorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderexecutor.OrderExecutorService/RequestVote',
            order__executor__pb2.VoteRequest.SerializeToString,
            order__executor__pb2.VoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderexecutor.OrderExecutorService/Heartbeat',
            order__executor__pb2.HeartbeatRequest.SerializeToString,
            order__executor__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExecutorStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderexecutor.OrderExecutorService/GetExecutorStatus',
            order__executor__pb2.StatusRequest.SerializeToString,
            order__executor__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
