# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\rorderexecutor\"I\n\x0bVoteRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x16\n\x0e\x63orrelation_id\x18\x03 \x01(\t\"2\n\x0cVoteResponse\x12\x14\n\x0cvote_granted\x18\x01 \x01(\x08\x12\x0c\n\x04term\x18\x02 \x01(\x05\"K\n\x10HeartbeatRequest\x12\x11\n\tleader_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x16\n\x0e\x63orrelation_id\x18\x03 \x01(\t\"2\n\x11HeartbeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04term\x18\x02 \x01(\x05\"\'\n\rStatusRequest\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\"w\n\x0eStatusResponse\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x14\n\x0c\x63urrent_term\x18\x03 \x01(\x05\x12\x18\n\x10processed_orders\x18\x04 \x01(\x05\x12\x11\n\tleader_id\x18\x05 \x01(\t2\x80\x02\n\x14OrderExecutorService\x12\x46\n\x0bRequestVote\x12\x1a.orderexecutor.VoteRequest\x1a\x1b.orderexecutor.VoteResponse\x12N\n\tHeartbeat\x12\x1f.orderexecutor.HeartbeatRequest\x1a .orderexecutor.HeartbeatResponse\x12P\n\x11GetExecutorStatus\x12\x1c.orderexecutor.StatusRequest\x1a\x1d.orderexecutor.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTEREQUEST']._serialized_start=39
  _globals['_VOTEREQUEST']._serialized_end=112
  _globals['_VOTERESPONSE']._serialized_start=114
  _globals['_VOTERESPONSE']._serialized_end=164
  _globals['_HEARTBEATREQUEST']._serialized_start=166
  _globals['_HEARTBEATREQUEST']._serialized_end=241
  _globals['_HEARTBEATRESPONSE']._serialized_start=243
  _globals['_HEARTBEATRESPONSE']._serialized_end=293
  _globals['_STATUSREQUEST']._serialized_start=295
  _globals['_STATUSREQUEST']._serialized_end=334
  _globals['_STATUSRESPONSE']._serialized_start=336
  _globals['_STATUSRESPONSE']._serialized_end=455
  _globals['_ORDEREXECUTORSERVICE']._serialized_start=458
  _globals['_ORDEREXECUTORSERVICE']._serialized_end=714
# @@protoc_insertion_point(module_scope)
